# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museo',
            name='accesibilidad',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='contacto',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='descripcion',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='descripcion_entidad',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='equipamiento',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='horario',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='identidad',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='localizacion',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='nombre',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='tipo',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='transporte',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
        migrations.AlterField(
            model_name='museo',
            name='url',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
    ]
