# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-19 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0009_auto_20180518_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleccion',
            name='propietario',
            field=models.CharField(max_length=30),
        ),
    ]
