# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-19 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0010_auto_20180519_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.TextField(default='DEFAULT_VALUE')),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museos.Museo')),
            ],
        ),
    ]
