# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-19 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0011_distrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrito',
            name='museo',
        ),
        migrations.AddField(
            model_name='museo',
            name='distrito',
            field=models.TextField(default='DEFAULT_VALUE'),
        ),
        migrations.DeleteModel(
            name='Distrito',
        ),
    ]
